### ISSUE TITLE
`$&sethistory` is slow (with readline)

### ISSUE THREAD

**Issue by jpco** [wryun/es-shell#133]
Pretty much the title.  My `.es-history` has hit some 50,000 lines now, and it seems to have slowed down starting up _es_ from ~3-5ms to ~70-90ms, which has become noticeable.  It also, naturally, eats quite a bit of memory.

What's worse (and what got me actually looking into this) is that slowdown (and extra memory usage) also affects non-interactive shell scripts.  Even the zero-byte script takes extra tens of milliseconds (and extra megabytes of RAM) to run with a large `$history` file, which isn't even used!

Perhaps it would be useful to delay calling `read_history()` until the first `callreadline()`; perhaps `stifle_history()` could be a smaller number (perhaps it could be a user-supplied number?); perhaps other shells like bash are doing something extra-clever that we could crib.

I've also noticed that _re_-setting history takes even longer.
```
; time {history = $history}
     0r     0.3u     0.0s	{history=$history}
```

**Comment by jpco** [comment]
Oh, I see... There are a few things going on here.

 - Firstly, it's still silly to read a potentially large history file into memory unless you're actually using it, so that's being changed.
 - Secondly, it seems that if you call `stifle_history(X)` and then `load_history(file)` where your file is `Y` lines long and `Y > X`, you end up calling `memmove`, on a memory region of size `X`, `Y - X` times.
 - Thirdly, the reason re-setting history takes longer is that once you've got all your `X` history lines populated, the next time you load a new file (which does _not_ clear the history in memory), you call `memmove` on your region of size `X` a full `Y` times!

It seems I was giving bash far too much credit -- it seems that their extra-clever mechanism for fast history loading was to just default `HISTSIZE=500` and `HISTFILESIZE=500`.  Performance is always good when you don't let your data set get big.  That said, it seems that if you `stifle_history(smallish number like 500)` then loading up a big file is still fast despite all the `memmove` calls.  So a simple fix is probably just to shrink the stifle size from `50000` to `5000`.

Also: I was surprised to see that running `history = x; history = y` would get you the contents of both `x` AND `y` in the history log.  Is that expected for anyone else?  Does it make sense to clear the in-memory history when `$history` is changed?

**Comment by memreflect** [comment]
> Also: I was surprised to see that running `history = x; history = y` would get you the contents of both `x` AND `y` in the history log. Is that expected for anyone else? Does it make sense to clear the in-memory history when `$history` is changed?

(Should that be a separate issue?)

How that is handled should be left up to `set-history` in my opinion.
I see a few options for changing this:

1. Make the `$&sethistory` primitive automatically clear the history list prior to reading a new history file, preventing that "merge" behavior from being customized.
   * Should this be done for `$&sethistory ()` as well?  (see #135)
2. Same as option 1, but additionally change `$&sethistory ()` to see multiple arguments as multiple files to be loaded, preserving the ability to utilize the merge behavior.
   * Should this be done for `$&sethistory ()` as well?  (see #135)
3. Make `$&sethistory ()` manually clear the history list, so `$&sethistory x ; $&sethistory y` would still load both `x` AND `y` without an invocation of `$&sethistory ()` between them.
4. Create a new `$&clearhistory` primitive to clear the history list instead of relying on any of the "magic" behaviors of `$&sethistory` above.
5. Do nothing because it's not a problem.

I'm not sure about options 1, 2 or 3 because `history = ()` would result in also clearing the history list; i thought it only controlled writing to the history file?
Avoiding that issue is also is not possible by customizing `set-history`: if `history = ()` avoids calling `$&sethistory ()`, the history list won't be cleared, but the history file will continue to be written, defeating the purpose of `history = ()`.
It's clear that appending the contents of a new history file to the history list is potentially confusing behavior as well, so option 5 is probably not a good fit, leaving only a new `$&clearhistory` primitive that could be used in `set-history` if desired.

That said, i'd be happy to hear other ideas so long as they don't involve a `$&history` "super-primitive", which is a loaded concept that definitely deserves its own separate discussion.

**Comment by jpco** [comment]
Here's an idea.  We could modify #134 to let a user clear the history list with the following:
```
fn clear-history {
  let (len = $max-history-length) {
    max-history-length = 0
    max-history-length = $len
  }
}
```
Currently #134 has `max-history-length = 0` special-cased to mean "no limit", but now I think that's redundant with just unsetting the variable, and it seems rather more useful to have it mean "clear the history list and don't add anything to it".  Then if someone wants history to be cleared when loading a new file, they could do so with
```
set-history = @ {
  clear-history
  $&sethistory $*
}
```
WDYT?  It's a little obscure, but otherwise it seems to cover all the bases nicely.  (I don't think I'd want to add `clear-history` to initial.es, but for illustration's sake.)  I think it does a good job keeping `history` focused on the history file, while `max-history-length` controls the history list.

Also, I thought you wrote somewhere about also having a form of limited-length history as `history = ~/.es-history 5000`.  Is it at all interesting for that to be used as an analog to `$HISTFILESIZE`, while `max-history-length` corresponds with `$HISTSIZE`?

**Comment by memreflect** [comment]
> Here's an idea. We could modify #134 to let a user clear the history list with the following:
> 
> ```
> fn clear-history {
>   let (len = $max-history-length) {
>     max-history-length = 0
>     max-history-length = $len
>   }
> }
> ```
> 
> Currently #134 has `max-history-length = 0` special-cased to mean "no limit", but now I think that's redundant with just unsetting the variable, and it seems rather more useful to have it mean "clear the history list and don't add anything to it". Then if someone wants history to be cleared when loading a new file, they could do so with
> 
> ```
> set-history = @ {
>   clear-history
>   $&sethistory $*
> }
> ```
> 
> WDYT? It's a little obscure, but otherwise it seems to cover all the bases nicely. (I don't think I'd want to add `clear-history` to initial.es, but for illustration's sake.) I think it does a good job keeping `history` focused on the history file, while `max-history-length` controls the history list.

Yes, i like that idea a lot, and i agree that initial.es doesn't need a `clear-history` function out of the box (include it as a "canonical example" maybe?)
I realize it's not as clean as having `$&sethistory` clear the list automatically, but it's a reasonable enough compromise between extensibility with `set-history`.

> Also, I thought you wrote somewhere about also having a form of limited-length history as `history = ~/.es-history 5000`. Is it at all interesting for that to be used as an analog to `$HISTFILESIZE`, while `max-history-length` corresponds with `$HISTSIZE`?

Yes, i recall mentioning such an idea, though i'm fairly confident that the best way to handle a `HISTFILESIZE` equivalent is to truncate the history file on shell termination and dump the last `$HISTFILESIZE` entries into it afterward.
History entries could not be written immediately because if `~ $HISTFILESIZE 500` and the file already contains 500 entries, you suddenly will exceed the limit.
The alternative to doing this on shell termination is doing this after every command once `HISTFILESIZE` is exceeded, which means for large values of `HISTFILESIZE`, there would be quite a delay.
That detail and how `HISTFILESIZE` might work without readline aside, i like the concept in theory, and `$&sethistory` currently only uses the first argument, making it a backward-compatible change if _es_ decided to switch to semantic versioning and had to consider backward-compatibility like that after v1.0.
