### ISSUE TITLE
Thunks incompletely deduplicated on parse

### ISSUE THREAD

**Issue by jpco** [wryun/es-shell#139]
This may be unbelievably nitpicky, but -- given the input:
```
; echo {{{{{{}}}}}}
```
I expect the output to be either `{}` or `{{{{{{}}}}}}`.  Instead, what I get is `{{{}}}`.

It seems `thunkify()` has a little logic to try to avoid adding redundant thunks.  That logic checks whether the argument `tree` is already a thunk, or is a list whose only element is a thunk -- in either case, it returns the input.  However, this gets defeated by repeated nesting, as more and more lists are added (so you go from `(thunk nil)` to `(list (thunk nil))` to `(list (list (thunk nil)))` and so on).

The behavior above can be narrowly resolved with a more thorough test for lists-containing-lists-containing-a-thunk in `thunkify`,
```
extern Tree *thunkify(Tree *tree) {
	Tree *t = tree;
	while (t != NULL && t->kind == nList && t->CDR == NULL)
		t = t->CAR;
	if (t != NULL && t->kind == nThunk)
		return tree;
	return mk(nThunk, tree);
}
```
But that change seems like a workaround for the actual weird behavior, which is all these redundant lists:
```
; ./es -Lc '{{{{{{}}}}}}'
(list (list (list (list (list (list (thunk nil)))))))
```
The extra lists are getting added by the `treecons2()` call in the `first -> simple` reduction.  If, instead of the `thunkify` change above, we make `treecons2(car, cdr)` a no-op if car is an `nList` and cdr is `NULL`, like
```
extern Tree *treecons2(Tree *car, Tree *cdr) {
	assert(cdr == NULL || cdr->kind == nList);
	if (car == NULL)
		return cdr;
	if (car->kind == nList && cdr == NULL)
		return car;
	return mk(nList, car, cdr);
}
```
then... that breaks `mkmatch()`, but if we also change the `word first -> case` reduction from a `mk(nList)` to a `mk(nMatch)`, then everything seems to work.  It's an egregious misapplication of `nMatch`, but all `mkmatch()` needs is a list of pairs irrespective of the type of pair.  (I'm also not convinced that using `nList` here wasn't a misuse of `nList` :)
```
./es -Lc '{{{{{{}}}}}}'
(list (thunk nil))
```
It's still very unclear to me whether changing `treecons2()` in this way is some kind of horrible violation of the logic of _es_' syntax-building that I'm not aware of with unintended consequences lurking -- that's why I'm filing this as an issue instead of sending a pull request.

**Comment by jpco** [comment]
It's unclear how thorough we would might want to be with this. Like, would the following be desirable too?
```
./es -Lc '{({({({})})})}'
(list (thunk nil))
```

**Comment by jpco** [comment]
Figured out how to achieve 
```
./es -Lc '{({({({})})})}'
(list (thunk nil))
```
This can be done by (in addition to the above changes) swapping out all calls to `treeconsend()` for `treeconsend2()`, and in `treconsend2()`, swapping the call to `treecons()` for `treecons2()`.  Technically for this case it's only the `treeconsend` call in the `nlwords` reduction that needs changed, but the same change in the `words` reduction simplifies the AST for things like `$(a (b (c)))` so it's also good.  Changing `params` is only for completeness; I don't think `params` can actually contain the nested structures required for the difference between `treeconsend` and `treeconsend2` to have any effect.

These last changes produce a non-zero change to the AST in initial.c -- however, the difference is negligible.  I think the difference is in the arg-parsing `if` in the definition of `fn vars` in initial.es.

What's more impactful is that all these changes together make it possible to get rid of `treecons()` and `treeconsend()` and replace them with the `2` versions of the functions.  (There are a few additional calls to `treecons()` that haven't been mentioned in this thread, but they're easily statically verifiably unaffected by switching to `treecons2()`.)  That seems like a simplicity/code-comprehensibility win to me; the two sets of functions have always been hard to reason about, and I would also argue the fact that the de-duplicating versions were named by just sticking a `2` on the end is evidence of this.

I think this is enough small improvements that a PR is worthwhile.

**Comment by memreflect** [comment]
> This may be unbelievably nitpicky, but -- given the input:
> 
> ```
> ; echo {{{{{{}}}}}}
> ```
> 
> I expect the output to be either `{}` or `{{{{{{}}}}}}`. Instead, what I get is `{{{}}}`.

Not nitpicky at all.
In fact, this is very much welcome as a step toward being able to eventually support tail recursion.

> The extra lists are getting added by the `treecons2()` call in the `first -> simple` reduction. If, instead of the `thunkify` change above, we make `treecons2(car, cdr)` a no-op if car is an `nList` and cdr is `NULL`, like
> 
> ```
> extern Tree *treecons2(Tree *car, Tree *cdr) {
> 	assert(cdr == NULL || cdr->kind == nList);
> 	if (car == NULL)
> 		return cdr;
> 	if (car->kind == nList && cdr == NULL)
> 		return car;
> 	return mk(nList, car, cdr);
> }
> ```
> 
> then... that breaks `mkmatch()`, but if we also change the `word first -> case` reduction from a `mk(nList)` to a `mk(nMatch)`, then everything seems to work. It's an egregious misapplication of `nMatch`, but all `mkmatch()` needs is a list of pairs irrespective of the type of pair. (I'm also not convinced that using `nList` here wasn't a misuse of `nList` :)

The reason i used `mk(nList)` was because `treecons()/treecons2()` creates pairs using `mk(nList, car, cdr)`, exactly like the `cons` function in Lisp.  ;)
The only difference between the two functions is that `treecons2()` simply returns `cdr` if `car` is NULL (e.g. `match X ( () {foo} () {bar} )` is turned into `match X ( {foo} {bar} )`).
As a result, i had to use the `treecons()` variant instead.
Since `cdr` is never null (it's at least an empty thunk), the assertion in `treecons()/treecons2()` will always be true, so i skipped it, which is probably a mistake on my part as it made things a bit more unclear.

Rationale aside, i have no issue with the node kind being changed to `nMatch`.
It is a suitable "close enough" alternative if it means other lists can be flattened earlier without breaking the `match` syntax.
I'm fairly certain this is the only place where something like lists of pairs containing lists are used anyway, so +1 to the `nMatch` change AND the de-duplication if it doesn't break things.

("Lists of pairs containing lists?"  Guess that makes me a 3-star programmer...and that's not usually a good thing! :)

> ```
> ./es -Lc '{{{{{{}}}}}}'
> (list (thunk nil))
> ```
> 
> It's still very unclear to me whether changing `treecons2()` in this way is some kind of horrible violation of the logic of _es_' syntax-building that I'm not aware of with unintended consequences lurking -- that's why I'm filing this as an issue instead of sending a pull request.

Well, _es_ flattens lists in the end anyway, so doing it early is more than likely a good optimization and unifies parse results with that flattening behavior.
Based on the code, the entire point of the "2" functions was to make those kinds of optimizations that the "non-2" functions will not.
