### ISSUE TITLE
Should `eval` be `$&noreturn`?

### ISSUE THREAD

**Issue by jpco** [wryun/es-shell#145]
Basically the title.  See the current behavior:
```
; echo <={@ {return 1; return 2}}
1
; echo <={@ {eval return 1; return 2}}
2
```
The following seems like it probably makes more sense:
```
; fn-eval = $&noreturn @ { '{' ^ $^* ^ '}' }
; echo <={@ {return 1; return 2}}
1
; echo <={@ {eval return 1; return 2}}
1
```
Do people agree?

**Comment by jpco** [comment]
(This is yet another thing noticed in the mailing list, see http://wryun.github.io/es-shell/mail-archive/msg00524.html)

**Comment by memreflect** [comment]
This question goes beyond just `eval`:

```
; echo <={es -xc 'return 99'}
99
```

`eval` definitely should be `$&noreturn`, but so should the replacement implementations of `$&readfrom` and `$&writeto` and even most of the predefined `%dispatch` hooks, excluding `%eval-noprint` and `%exit-on-false`.

`fork`, `%background` and `%backquote` are all fine because they execute their commands in a child shell anyway, so they're `$&noreturn` as a side effect.
I'm fairly certain all other functions are ok the way they are as well, but i could be wrong.

**Comment by jpco** [comment]
> most of the predefined `%dispatch` hooks

Agreed, `%dispatch` should be `$&noreturn` in general.  Technically the hooks themselves don't need to be `$&noreturn`; that can be handled by the "hooking" behavior in `input.c`.  Likely, it's more straightforward to just change the hooks, though. `status.es` should get an update to handle the `return` exception as well, I missed that the first time around.

> the replacement implementations of `$&readfrom` and `$&writeto`

I'm not sure about this one.  I think, ideally, `%readfrom` and `%writeto` should have a consistent interface irrespective of its implementation.  It actually didn't occur to me till now the non-primitive versions don't fork... it would be simple to make things consistent if they did.  Better yet, it would be nice if they could be forked and then waited-for after the command finished, but I don't think _es_ primitives (particularly `$&background`) are flexible enough to make that happen correctly right now.  I have some ideas in that regard, but they require some careful thinking about pipes that I haven't done.

Wait, I just realized you were talking about `return <{true}` and not `echo <{return true}`.  Yes, I agree with you there. :)  Leaving my other thoughts up, though, because the second case is also odd/inconsistent.
