### ISSUE TITLE
Build on OpenBSD fails, miserably

### ISSUE THREAD

**Issue by vl-ms** [wryun/es-shell#46]
Once I figured out that the OpenBSD version of es is the original one, I attempted to build your version instead.
The problem is, after executing 
```
libtoolize -qi
autoreconf
```
the configure script does not magically appear, as promised. Only configure.ac is there from the start.
What should I do now?

**Comment by wryun** [comment]
What's the output from the above commands?

**Comment by memreflect** [comment]
OpenBSD requires you to use environment variables to indicate which version of Autoconf and Automake to use, so it looks like this for me with automake-1.16.5 installed on OpenBSD 7.2:

```
ksh$ export AUTOCONF_VERSION=2.69 AUTOMAKE_VERSION=1.16
ksh$ libtoolize -qi
ksh$ autoreconf
```

If you are uncertain which versions of Automake and Autoconf you have installed, [pkg_info(1)](https://man.openbsd.org/pkg_info.1) can help:

```
ksh$ pkg_info -I automake autoconf
automake-1.16.5     GNU Standards-compliant Makefile generator
autoconf-2.69p3     automatically configure source code on many Un*x platforms
```

**Comment by vl-ms** [comment]
ah, the issue was that I used 2.71 autoconf, not 2.69 (nice) as you do. Got it. Maybe it's worth it to add into docs that exactly 2.69 is needed?

**Comment by memreflect** [comment]
> Maybe it's worth it to add into docs that exactly 2.69 is needed?

Technically it isn't.
2.71 displays warnings with a bunch of additional info, but these are not errors that prevent generation of configure or config.h.in:

```
ksh$ export AUTOCONF_VERSION=2.71 AUTOMAKE_VERSION=1.16
ksh$ libtoolize -qi
ksh$ autoreconf
configure.ac:4: warning: The macro `AC_CONFIG_HEADER' is obsolete.
configure.ac:4: You should run autoupdate.
/usr/local/share/autoconf-2.71/autoconf/status.m4:719: AC_CONFIG_HEADER is expanded from...
configure.ac:4: the top level
configure.ac:81: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:81: You should run autoupdate.
/usr/local/share/autoconf-2.71/autoconf/headers.m4:712: AC_HEADER_STDC is expanded from...
configure.ac:81: the top level
configure.ac:96: warning: AC_FUNC_WAIT3: `wait3' has been removed from POSIX.
configure.ac:96: Remove this `AC_FUNC_WAIT3' and adjust your code to use `waitpid' instead.
/usr/local/share/autoconf-2.71/autoconf/functions.m4:2103: AC_FUNC_WAIT3 is expanded from...
configure.ac:96: the top level
```

These warnings can be silenced by using `autoreconf --warnings=none` if this is a problem.

The alternative would be to accept the suggestion and run `autoupdate`, but using that with `AUTOCONF_VERSION=2.71` would make 2.71 a hard requirement due to the use of `AC_CHECK_INCLUDES`.
`autoupdate` also doesn't prevent the warning about `AC_FUNC_WAIT3`, so silencing the warnings is probably the easiest remedy while ensuring compatibility with older versions of Autoconf.

**Comment by vl-ms** [comment]
weird, previously 2.71 produced no errors for me, but also no 'configure'. Now I checked and yeah, it works. I guess something is wrong with me
